-- 家族表
CREATE TABLE IF NOT EXISTS "family"
(
    "id"            bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '主键ID',
    "name"           varchar(100) NOT NULL COMMENT '家族名称',
    "main_surname"   varchar(50)   NOT NULL COMMENT '主要姓氏',
    "location"       varchar(200) DEFAULT NULL COMMENT '祖籍位置',
    "desc"           text         COMMENT '家族简介/家训',
    "cover_url"      varchar(512)  DEFAULT NULL COMMENT '封面图URL',
    "creator_id"     bigint       NOT NULL COMMENT '创建者UserID',
    "status"         tinyint      NOT NULL DEFAULT '0' COMMENT '状态: 0待审, 1正常, 2拒绝, 3删除',
    "privacy_level" tinyint      DEFAULT '0' COMMENT '隐私: 0公开, 1仅族人可见',
    "tenant_id"      bigint       NOT NULL DEFAULT '0' COMMENT '租户ID(保留字段)',
    "create_time"    datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"    datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "creator"        varchar(64)  NULL     DEFAULT '',
    "updater"        varchar(64)  NULL     DEFAULT '',
    "deleted"        bit(1)       NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
) COMMENT='家族信息表';

-- 成员表
CREATE TABLE IF NOT EXISTS "member"
(
    "id"                      bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "family_id"               bigint       NOT NULL COMMENT '所属家族ID',
    "name"                    varchar(50)  NOT NULL COMMENT '姓名',
    "gender"                  tinyint      NOT NULL COMMENT '性别: 1男, 0女',
    "generation_level"        int          DEFAULT NULL COMMENT '字辈/第几世',
    "birth_date"              date         DEFAULT NULL COMMENT '出生日期',
    "death_date"              date         DEFAULT NULL COMMENT '去世日期',
    "is_alive"                bit(1)        DEFAULT b'1' COMMENT '是否健在',
    "avatar_url"              varchar(512) DEFAULT NULL COMMENT '头像',
    "biography"               text         COMMENT '人物行传/生平',
    "father_id"               bigint       DEFAULT NULL COMMENT '父亲ID (冗余,便于快速构建树)',
    "mother_id"               bigint       DEFAULT NULL COMMENT '母亲ID (冗余)',
    "parent_family_unit_id"   bigint       DEFAULT NULL COMMENT '所属的原生家庭单元ID',
    "sort"                    int          DEFAULT '0' COMMENT '排序(长幼顺序)',
    "create_time"             datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"             datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "creator"                 varchar(64)  NULL     DEFAULT '',
    "updater"                 varchar(64)  NULL     DEFAULT '',
    "deleted"                 bit(1)       DEFAULT b'0',
    PRIMARY KEY ("id")
) COMMENT='家族成员表';

-- 家庭单元表
CREATE TABLE IF NOT EXISTS "family_unit"
(
    "id"            bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "family_id"     bigint      NOT NULL,
    "husband_id"    bigint      NOT NULL COMMENT '丈夫ID',
    "wife_id"       bigint      DEFAULT NULL COMMENT '妻子ID (可为空,如未婚生子)',
    "wife_name"     varchar(50) DEFAULT NULL COMMENT '妻子姓名(若妻子未录入系统)',
    "marriage_date" date        DEFAULT NULL COMMENT '结婚日期',
    "status"        tinyint     DEFAULT '1' COMMENT '状态: 1婚姻中, 0离异, 2丧偶',
    "sort"          int         DEFAULT '0' COMMENT '配偶排序(原配/续弦)',
    "create_time"   datetime    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"   datetime    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "creator"       varchar(64) NULL     DEFAULT '',
    "updater"       varchar(64) NULL     DEFAULT '',
    "deleted"       bit(1)      DEFAULT b'0',
    PRIMARY KEY ("id")
) COMMENT='家庭单元(婚姻)表';

-- 审核记录表
CREATE TABLE IF NOT EXISTS "audit_log"
(
    "id"             bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "family_id"      bigint      NOT NULL,
    "applicant_id"  bigint      NOT NULL COMMENT '申请人ID',
    "entity_type"    varchar(20) NOT NULL COMMENT 'MEMBER / FAMILY',
    "entity_id"      bigint      DEFAULT NULL COMMENT '关联实体ID(新增时为空)',
    "operation_type" varchar(20) NOT NULL COMMENT 'CREATE / UPDATE / DELETE',
    "old_json"      text        DEFAULT NULL COMMENT '修改前数据快照',
    "new_json"       text        NOT NULL COMMENT '期望修改后数据',
    "audit_status"   tinyint     DEFAULT '0' COMMENT '0待审, 1通过, 2驳回',
    "audit_comment"  varchar(255) DEFAULT NULL COMMENT '驳回原因',
    "auditor_id"     bigint      DEFAULT NULL COMMENT '审核人ID',
    "audit_time"     datetime    DEFAULT NULL,
    "create_time"    datetime    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
) COMMENT='业务审核记录表';

-- 家族成员关系表
CREATE TABLE IF NOT EXISTS "family_member"
(
    "id"            bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "family_id"     bigint      NOT NULL COMMENT '家族ID',
    "user_id"       bigint      NOT NULL COMMENT '用户ID',
    "role"          tinyint     DEFAULT '0' COMMENT '角色: 0普通成员, 1家族管理员',
    "create_time"   datetime    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"   datetime    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "creator"       varchar(64) NULL     DEFAULT '',
    "updater"       varchar(64) NULL     DEFAULT '',
    "deleted"       bit(1)      DEFAULT b'0',
    PRIMARY KEY ("id"),
    UNIQUE KEY ("family_id", "user_id")
) COMMENT='家族成员关系表';

